### ISSUE TITLE
Pachyderm Git input blocked: can't provision LoadBalancer

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/pachyderm#1]
This feature

https://docs.pachyderm.com/latest/reference/pipeline_spec/#git-input-alpha-feature

Would be super helpful for Ken's workflow, but at the moment is doesn't work because it tries to create a loadbalancer (which is justifiably not allowed). The LoadBalancer is just to create the webhook. Here is an example of the error message.

```
context:(default) >>> inspect pipeline wifr-sensitivity                                                                                                               [28/150]
Name: wifr-sensitivity                                                                                                                                                        
Description: Create wifr simulation from input random seeds                                                                                                                   
Created: About a minute ago                                                                                                                                                   
State: failure                                                                                                                                                                
Stopped: false                                                                                                                                                                
Reason: failed to create RC/service after 3 attempts: services "githook" is forbidden: exceeded quota: service-quota, requested: services.loadbalancers=1,services.nodeports=1
, used: services.loadbalancers=0,services.nodeports=0, limited: services.loadbalancers=0,services.nodeports=0                                                                 
Parallelism Spec: constant:2                                                                                                                                                  
Datum Timeout: (duration: nil Duration)                                                                                                                                       
Job Timeout: (duration: nil Duration)                                                                                                                                         
Input:                                                                                                                                                                        
{                                                                                                                                                                             
  "cross": [                                                                                                                                                                  
    {                                                                                                                                                                         
      "git": {                                                                                                                                                                
        "name": "git",                                                                                                                                                        
        "url": "https://github.com/kennethchu-statcan/covid19-pachyderm.git",                                                                                                 
        "branch": "master"                                                                                                                                                    
      }                                                                                                                                                                       
    },                                                                                                                                                                        
    {                                                                                                                                                                         
      "pfs": {                                                                                                                                                                
        "name": "data",                                                                                                                                                       
        "repo": "wifr-data",                                                                                                                                                  
        "branch": "2020-04-24_01",                                                                                                                                            
        "glob": "/"                                                                                                                                                           
      }                                    
    },                                                                                 
    {                                    
      "pfs": {                                                                         
        "name": "params",                                                              
        "repo": "wifr-params",                                                                                                                                                
        "branch": "master",                                                                                                                                                   
        "glob": "/*/*"                                                                                                                                                        
      }                                                                                                                                                                       
    }                                                                                                                                                                         
  ]                                                                                                                                                                           
}    
```

Here's what I found looking at the source code

https://github.com/pachyderm/pachyderm/blob/d9554ff47a3e98558a29c16a94d00536e0cadb66/src/server/pps/server/api_server.go#L2382

**If you could let me know if you have time to look at this that would be great; this is a blocker for Ken, and I can find an alternative route if necessary. But this feature would be great if it's a fast fix.**

**Comment by blairdrummond** [comment]
Here is a pipeline to test with; it will fail right away if the githook isn't working.

```
pipeline:
  name: wifr-sensitivity
description: "Create wifr simulation from input random seeds"
#standby: true
transform:
  image: k8scc01covidacr.azurecr.io/kenchu-wifr-git:v1
  image_pull_secrets:
    - k8scc01covidacr-registry-connection
  cmd:
    - "/main.sh"
    - "--src"
    - "/pfs/git/src/"
    - "--params"
    - "/pfs/params/"
    - "--data"
    - "/pfs/data/"
    - "--output"
    - "/pfs/out"
#resource_requests:
#  memory: "4G"
#  cpu: 2
#resource_limits:
#  memory: "6G"
#  cpu: 3
parallelism_spec:
  constant: 2  # use N computers
output_branch: 2020-04-24_01
input:
  cross:
    - pfs:
        name: params
        repo: wifr-params
        glob: "/*/*"
    - pfs:
        name: data
        repo: wifr-data
        glob: "/"
        branch: 2020-04-24_01
    - git:
        url: "https://github.com/kennethchu-statcan/covid19-pachyderm.git"
        name: git
        branch: master
```

(launch with `pachctl create pipeline -f thatfile.yaml`)
